### ISSUE TITLE
Part 1 - Missing some code explanation

### ISSUE THREAD

**Issue by vorant94** [TStand90/roguelike_tutorial_revised#19]
At the end, where we use our defined console instead of the default one (`0`), there is this line of code and not a single word about it:

`libtcod.console_put_char(con, player_x, player_y, ' ', libtcod.BKGND_NONE)`

Even after it is marked not as new but the modified line, there is no word about its previous version neither.

I understand that it clears old `@` from the console, but since I am a newbie I can't figure out why it just simply doesn't erase also the current `@`? It has the same coordinates after all!

**Comment by TeddybearJunction** [comment]
Hi @vorant94, 

The console is actually a buffer (The documentation for console_new mentions it's an "off-screen console"). When you "put_char" you're adding it to that buffer. The buffer won't be displayed on your screen until you "flush" the buffer to the screen. 

So, with that info, check out this outline of what happens and when:

create the new console

enter game loop
--add player icon @ to the off-screen console
--flush (display!) the console including our changes from above
--clear out the place where our player was in the last update.
--move the player (i.e. now the @ icon will be moved to the new location

So now that the player has moved, we'll draw him/her at his/her new location, and there won't be an after image, because we already cleared the spot where s/he was before.

That's definitely not a perfect answer, but I hope it helps!
