### ISSUE TITLE
TDL tutorial Chapter 8 - Function call for inventory_menu missing arg

### ISSUE THREAD

**Issue by MelSavage** [TStand90/roguelike_tutorial_revised#4]
Hi! Thank you so much for this great tutorial! I've been learning a lot and really enjoying it!

I had a problem halfway in Chapter 8 getting an error because it said a positional argument was missing from the function call for inventory_menu. This function call is located within the render_all function's definition, the following lines:

    if game_state == GameStates.SHOW_INVENTORY:
        inventory_menu(con, 'Press the key next to an item to use it, or Esc to cancel.\n',
                       player.inventory, 50, screen_width, screen_height)

It's missing an argument for the root console. I believe it should read as this, instead:

    if game_state == GameStates.SHOW_INVENTORY:
        inventory_menu(con, root_console,  'Press the key next to an item to use it, or Esc to cancel.\n',
                       player.inventory, 50, screen_width, screen_height) 

I should note that this error is in the tutorial on http://rogueliketutorials.com/tdl/8. I figured this was a good way to contact you. I don't have a Reddit account, actually. I assume that it's not in GitHub code. Thanks!!!

**Comment by MelSavage** [comment]
Also in Chapter 8, defining the new handle_keys function uses "key" as the first argument, but then passes "user_input" to the function calls within it

Also, reads modifying the call to handle_keys in engine.py as if the first argument (which is not in green, so should not be modified) is "key," when it is actually "user_input." Both of these should read "user_input"

**Comment by TStand90** [comment]
Yep, you're right on both accounts. Looks like this was a case of me rushing to get both the libtcod and tdl versions of this tutorial done.

The first issue, the tdl tutorial passes "root_console", but the libtcod one doesn't. So I must have copied the line from the libtcod version without adding the argument.

As for the second, the libtcod version uses "key" whereas the tdl one uses "user_input", so when I was copying one set of tutorial instructions over, I failed to double-check the variable names.

I've updated the tutorial to address both these issues. Thank you very much for bringing this to my attention! In the near future, I plan on publishing the tutorial's website (or at least the markdown files of the pages) to Github so that they'll have a better place for tutorial specific issues. Until now, feel free to continue posting issues here.
